# : Manager [[[

[manager]
cwd = { fg = "#e9e2d4" }

# Tab
tab_active = { fg = "#3a3000", bg = "#dcc66e", bold = true }
tab_inactive = { fg = "#f9e287", bg = "#221b00" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#78d38d", bg = "#78d38d" }
marker_cut = { fg = "#c5ecce", bg = "#c5ecce" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#aad0b3", bg = "#aad0b3" }

# Count
count_copied = { fg = "#00210f", bg = "#c5ecce" }
count_cut = { fg = "#00210f", bg = "#c5ecce" }
count_selected = { fg = "#3a3000", bg = "#aad0b3" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#dcc66e" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#3a3000", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#dcc66e", fg = "#3a3000", bold = true }
normal_alt  = { bg = "#4b4739", fg = "#cdc6b4" }

# Select mode
select_main = { bg = "#d1c6a1", fg = "#373016", bold = true }
select_alt  = { bg = "#4b4739", fg = "#cdc6b4" }

# Unset mode
unset_main = { bg = "#aad0b3", fg = "#153722", bold = true }
unset_alt  = { bg = "#4b4739", fg = "#cdc6b4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#dcc66e", bg = "#3c3930" }
progress_error = { fg = "#ffb4ab", bg = "#3c3930" }

# Permissions
permissions_t = { fg = "#928147" }
permissions_w = { fg = "#50915f" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#52c66d" }
permissions_s = { fg = "#dcb20b" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#dcc66e" }
active = { fg = "#aad0b3", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#dcc66e" }
value = { fg = "#e9e2d4" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#dcc66e", bg = "#3a3000" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#dcc66e" }
title = {}
hovered = { fg = "#c5ecce", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3c3930" }
cand = { fg = "#dcc66e" }
rest = { fg = "#3a3000" }
desc = { fg = "#e9e2d4" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e9e2d4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e9e2d4" }
run = { fg = "#e9e2d4" }
footer = { fg = "#373016", bg = "#d1c6a1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#aad0b3" }
title_warn = { fg = "#dcc66e" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e9e2d4" },
    { name = "*/", fg = "#dcc66e" },
]

# : ]]]